on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate AppStream file
        run: |
          appstreamcli validate --no-net data/io.github.kelvinnovais.Kasasa.metainfo.xml.in
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: kasasa.flatpak
          manifest-path: io.github.kelvinnovais.Kasasa.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
